name: dev

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_NAME: ossranker
      SKIP_ENV_VALIDATION: 1
      NEXT_PUBLIC_STACK_PROJECT_ID: 4e30732f-9da3-4593-b938-d3bb3938cd59
      NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY: pck_aq7tkqebk4mdxcgxfhybfrk25tdhjrf5n8ztc0g57prpr
      NEXT_PUBLIC_SITE_URL: https://alpha.ossranker.io/
      NEXT_PUBLIC_GIT_SHA: ${{ github.sha }}
    steps:
      - name: "Get branch name and save to env"
        env:
          IS_PR: ${{ github.EVENT_NAME == 'pull_request' }}
        run: |
          if ${IS_PR}; then
            TAG="${GITHUB_HEAD_REF}"
          else
            TAG="${GITHUB_REF##*/}"
          fi
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.6.5

      - uses: actions/cache@v3
        name: Setup pnpm cache
        id: cache-next-restore
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - uses: actions/setup-node@v4
        with:
          node-version: 22.10.0
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: swr.ap-southeast-3.myhuaweicloud.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: swr.ap-southeast-3.myhuaweicloud.com
          name: scantist-images/${{ env.APP_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "${{ env.TAG }},PROD-DEV"
    outputs:
      tag: ${{ env.TAG }}
      app_name: ${{ env.APP_NAME }}

  update:
    runs-on: ubuntu-latest
    env:
      GKE_CLUSTER_NAME: v4-staging-gke
      GKE_CLUSTER_ZONE: asia-southeast1-b
      GKE_PROJECT_ID: scantist-v4-staging
      GKE_CLUSTER_NAMESPACE: ossranker
      IMAGE_REPO: swr.ap-southeast-3.myhuaweicloud.com/scantist-images
    needs: build
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.V4_STAGING_GKE_JSON }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 513.0.0'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GKE_CLUSTER_ZONE }}
          namespace: ${{ env.GKE_CLUSTER_NAMESPACE }}
          project_id: ${{ env.GKE_PROJECT_ID }}
      - name: 'Set Image and Restart Deployment'
        run: |
          APP_NAME="${{ needs.build.outputs.app_name }}"
          IMAGE_TAG="${{ needs.build.outputs.tag }}"
          IMAGE_NAME="${{ env.IMAGE_REPO }}/${APP_NAME}:${IMAGE_TAG}"
